[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
name = "web"

[services.variables]
PORT = "5000"

# Add start command for the Flask app using gunicorn
[services.start]
command = "gunicorn app:app --bind 0.0.0.0:$PORT"